// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7GksaGakue80y_Sjrh8r2YFfao8e4e6M',
    appId: '1:272985112411:web:c035fbaddd3cef618c647e',
    messagingSenderId: '272985112411',
    projectId: 'fs-practice-4c7c5',
    authDomain: 'fs-practice-4c7c5.firebaseapp.com',
    storageBucket: 'fs-practice-4c7c5.appspot.com',
    measurementId: 'G-PZ8T4EV0GC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj2up0PvDat7UZKGRmEsrW83SNicXKqv8',
    appId: '1:272985112411:android:4c96a5e051c0dacc8c647e',
    messagingSenderId: '272985112411',
    projectId: 'fs-practice-4c7c5',
    storageBucket: 'fs-practice-4c7c5.appspot.com',
  );
}
